#!/bin/bash
cellsize=4
bond_const=`seq 4.15667 .2 6.15667`
angle_const=`seq 0.171 .2 2.171`
num_del={0,35}
atom=bond
guide=0
deldist=0

runjob()
{
   mkdir -p $PARALLEL_PID$PARALLEL_SEQ
   cd $PARALLEL_PID$PARALLEL_SEQ
   cp ../inputfiles/* .
   cp potential.mod potential.mod.orig
   input=`generator silicon 5 $1 $2 $3 $4 $5 | awk '{ if (/^Density/) print $2; if (/^Bond) print $3; if (/^Average/) print $3; if (/^Num Coord/) print $4; if (/^Avg Coord/) print $6 }'`
   awk "{ if (/^bond_coeff/) \$3 = $6; if (/^angle_coeff/) \$3 = $7; print}" potential.mod.orig > potential.mod
   results=`lammps < in.elastic | awk '{ if (/^Elastic Constant C(11|22|33|12|13|23|44|55|66)/) { print $5 } }'`
   output=$6' '$7' '$input' '$results
   echo $output
   cd ..
   rm -rf $PARALLEL_PID$PARALLEL_SEQ
}
export -f runjob
parallel --gnu runjob ::: $cellsize ::: $num_del ::: $atom ::: $guide ::: $deldist ::: $bond_const ::: $angle_const ::: {1..20}
rm -rf 1*
rm -rf 2*
rm -rf 3*
rm -rf 4*
rm -rf 5*
rm -rf 6*
rm -rf 7*
rm -rf 8*
rm -rf 9*
